CREATE TABLE Aerodromi (
	AerodromID SERIAL PRIMARY KEY,
	Naziv VARCHAR(255),
	Grad VARCHAR(255),
	KapacitetPiste INT,
	KapacitetSkladista INT
);

CREATE TABLE Avioni (
	AvionID SERIAL PRIMARY KEY,
	Naziv VARCHAR(255),
	Model VARCHAR(255),
	Kapacitet INT,
	Status VARCHAR(50)
);

ALTER TABLE Letovi
ADD COLUMN OsobljeID INT REFERENCES Osoblje(OsobljeID);

CREATE TABLE Korisnici (
	UserID SERIAL PRIMARY KEY,
	Ime VARCHAR(255),
	LoyaltyKartica BOOLEAN,
	BrojKupljenihKarata INT
);

CREATE TABLE Karte (
	KartaID SERIAL PRIMARY KEY,
	UserID INT REFERENCES Korisnici(UserID),
	LetID INT REFERENCES Letovi(LetID),
	Cijena DECIMAL(10, 2),
	Mjesto VARCHAR(10)
);

CREATE TABLE Letovi (
	LetID SERIAL PRIMARY KEY,
	AvionID INT REFERENCES Avioni(AvionID),
	PolazniAerodromID INT REFERENCES Aerodromi(AerodromID),
	DolazniAerodromID INT REFERENCES Aerodromi(AerodromID),
	DatumPolaska DATE,
	DatumDolaska DATE,
	Ocjena INT,
	Komentar TEXT
);

ALTER TABLE Letovi
ADD COLUMN OsobljeID INT REFERENCES Osoblje(OsobljeID);

CREATE OR REPLACE FUNCTION check_crew_per_flight()
RETURNS BOOLEAN AS $$
DECLARE
    crew_count INT;
BEGIN
    SELECT COUNT(*) INTO crew_count
    FROM Osoblje AS O
    JOIN Letovi AS L ON O.OsobljeID = L.OsobljeID
    WHERE (
        (O.Vrsta = 'Pilot' AND L.PilotID = O.OsobljeID) OR
        (O.Vrsta = 'Stjuardesa' AND L.StjuardesaID = O.OsobljeID)
    ) AND (
        (L.DatumPolaska <= NEW.DatumPolaska AND L.DatumDolaska >= NEW.DatumPolaska) OR
        (L.DatumPolaska <= NEW.DatumDolaska AND L.DatumDolaska >= NEW.DatumDolaska)
    );

    RETURN crew_count = 0;
END;
$$ LANGUAGE plpgsql;

ALTER TABLE Letovi
ADD CONSTRAINT UniqueCrewPerFlight
CHECK (check_crew_per_flight());

ALTER TABLE Letovi
ADD CONSTRAINT CheckRating
CHECK (Ocjena >= 1 AND Ocjena <= 5);

CREATE TABLE Osoblje (
	OsobljeID SERIAL PRIMARY KEY,
	Ime VARCHAR(255),
	Prezime VARCHAR(255),
	Vrsta VARCHAR(50),
	Godine INT,
	BrojOdradenihLetova INT,
	Placa DECIMAL(10, 2)
);

ALTER TABLE Osoblje
ADD CONSTRAINT CheckPilotAge
CHECK (Vrsta = 'Pilot' AND Godine >= 20 AND Godine <= 60)

INSERT INTO Aerodromi (Naziv, Grad, KapacitetPiste, KapacitetSkladista) VALUES 
		('Teruel Airport','Teruel',78,119),
		('Prince Albert Glass Field','Prince Albert',88,600),
		('Sivas Nuri Demirağ Airport','Sivas',93,774),
		('Matari Airport','',58,819),
		('Whalsay Airport','Whalsay',44,383),
		('Lauro Kurtz Airport','Passo Fundo',7,562),
		('Tshikapa Airport','Tshikapa',98,517),
		('El Arish International Airport','El Arish',33,365),
		('Quartz Hill Airport','Lancaster',43,389),
		('Mélio Viana Airport','Três Corações',69,724),
		('El Palomar Airport','El Palomar',97,672),
		('Bokoro Airport','Bokoro',31,819),
		('Brest Airport','Brest',48,548),
		('Bumi Airport','Bumi',21,66),
		('Kerikeri Airport','Kerikeri',42,931),
		('Long Lellang Airport','Long Datih',99,89),
		('Torrington Municipal Airport','Torrington',6,918),
		('Mweka Airport','Mweka',61,123),
		('Defiance Memorial Airport','Defiance',83,148),
		('Tlokoeng Airport','Tlokoeng',39,378),
		('Lviv International Airport','Lviv',65,651),
		('Timber Creek Airport','',18,775),
		('Jinnah International Airport','Karachi',8,526),
		('Marechal Cunha Machado International Airport','São Luís',61,677),
		('Muscat International Airport','Muscat',76,312),
		('Mtwara Airport','Mtwara',7,747),
		('Namrole Airport','Namrole-Buru Island',64,950),
		('Nador International Airport','Nador',31,455),
		('Motswari Airport','Motswari Private Game Reserve',38,486),
		('Bost Airport','Bost',16,464),
		('Mauke Airport','Mauke Island',13,864),
		('Reid-Hillview Airport of Santa Clara County','San Jose',81,65),
		('Los Roques Airport','Gran Roque Island',54,856),
		('King Island Airport','',95,394),
		('Copper Center 2 Airport','Copper Center',71,518),
		('Kilwa Airport','Kilwa',94,432),
		('Chios Island National Airport','Chios Island',1,599),
		('Loncopue Airport','Loncopue',77,159),
		('Mayo Airport','Mayo',29,377),
		('Campbell River Airport','Campbell River',82,684),
		('Battle Mountain Airport','Battle Mountain',75,238),
		('Unalakleet Airport','Unalakleet',12,849),
		('Aseki Airport','Aseki',61,713),
		('Dangriga Airport','Dangriga',98,729),
		('Nadi International Airport','Nadi',84,307),
		('Baidoa Airport','Baidoa',31,836),
		('Decatur Airport','Decatur',8,67),
		('Vanrook Station Airport','',3,11),
		('Peterborough Airport','Peterborough',58,33),
		('Kaltag Airport','Kaltag',54,172),
		('Funafuti International Airport','Funafuti',79,672),
		('Ileg Airport','Ileg',32,343),
		('Alfonso López Pumarejo Airport','Valledupar',97,274),
		('Mackay Airport','Mackay',100,544),
		('Waikoloa Heliport','Waikoloa Village',25,470),
		('Rae Lakes Airport','Gamètì',49,2),
		('Jutigalpa airport','Jutigalpa',3,439),
		('Larisa Airport','Larisa',11,195),
		('Forest City Municipal Airport','Forest City',76,274),
		('Antwerp International Airport (Deurne)','Antwerp',32,567),
		('Jiamusi Airport','Jiamusi',87,154),
		('Tuguegarao Airport','Tuguegarao City',95,461),
		('Lakefront Airport','New Orleans',78,205),
		('Open Bay Airport','Maitanakunai',43,196),
		('Reyes Murillo Airport','Nuquí',14,217),
		('Sept-Îles Airport','Sept-Îles',23,27),
		('Chişinău International Airport','Chişinău',21,654),
		('RAF Alconbury','Huntingdon',90,822),
		('Murray Island Airport','Murray Island',9,385),
		('Luena Airport','Luena',49,975),
		('Vilo Acuña International Airport','Cayo Largo del Sur',37,804),
		('Kurumoch International Airport','Samara',82,595),
		('Gustavo Rizo Airport','Baracoa',83,698),
		('Fuerte Olimpo Airport','Fuerte Olimpo',72,325),
		('Leipzig/Halle Airport','Leipzig',20,124),
		('Sayaboury Airport','Sainyabuli',75,998),
		('Tiom Airport','Tiom-Papua Island',100,436),
		('Kentland Municipal Airport','Kentland',71,710),
		('Manuel Márquez de León International Airport','La Paz',72,637),
		('Taitung Airport','Taitung City',93,517),
		('Dilasag Airport','Dilasag',4,484),
		('Sugar Land Regional Airport','Houston',85,124),
		('Chichester/Goodwood Airport','Chichester',13,616),
		('Los Cerrillos Airport','Santiago',63,413),
		('Belbek Airport','Sevastopol',44,788),
		('Laconia Municipal Airport','Laconia',39,70),
		('Maury County Airport','Columbia/Mount Pleasant',66,561),
		('Bogashevo Airport','Tomsk',82,240),
		('Porto Amboim Airport','Port Amboim',80,383),
		('Escuela Mariscal Sucre Airport','Maracay',85,331),
		('Sucua Airport','Sucua',71,449),
		('Ozona Municipal Airport','Ozona',13,350),
		('Blackpool International Airport','Blackpool',7,846),
		('Gurupi Airport','Gurupi',39,731),
		('Brookings Airport','Brookings',91,873),
		('Teminabuan Airport','Atinjoe-Papua Island',71,940),
		('Bildudalur Airport','Bildudalur',16,675),
		('Sebba Airport','Sebba',6,361),
		('Riesa-Göhlis Airport','Riesa',88,27),
		('Wallal Airport','Wallal',18,783),
		('Brigadeiro Lysias Rodrigues Airport','Palmas',25,319),
		('Palmyra Airport','Tadmur',76,411),
		('Qikiqtarjuaq Airport','Qikiqtarjuaq',38,495),
		('Bahías de Huatulco International Airport','Huatulco',49,639),
		('Augsburg Airport','Augsburg',75,862),
		('Sardar-e-Jangal Airport','Rasht',64,667),
		('March ARB Airport','Riverside',3,591),
		('El Tepual Airport','Puerto Montt',42,161),
		('Exmouth Airport','',75,404),
		('Queen Beatrix International Airport','Oranjestad',15,437),
		('Humberto Ghizzo Bortoluzzi Regional Airport','Jaguaruna',70,345),
		('Gorno-Altaysk Airport','Gorno-Altaysk',38,769),
		('W K Kellogg Airport','Battle Creek',19,129),
		('Boswell Bay Airport','Boswell Bay',35,374),
		('Namatanai Airport','Namatanai',91,763),
		('Delaware County Johnson Field','Muncie',73,571),
		('Seguela Airport','Seguela',49,404),
		('Ngot Nzoungou Airport','Dolisie',25,377),
		('Jyvaskyla Airport','Jyväskylän Maalaiskunta',50,944),
		('San José De Chiquitos Airport','San José de Chiquitos',64,856),
		('Muscatine Municipal Airport','Muscatine',94,345),
		('Whiting Field Naval Air Station - North','Milton',36,199),
		('Toyama Airport','Toyama',16,826),
		('Tri-State/Milton J. Ferguson Field','Huntington',80,841),
		('Pevek Airport','Pevek',80,497),
		('St Thomas Municipal Airport','St Thomas',42,170),
		('Kajaani Airport','Kajaani',75,575),
		('Mayor Buenaventura Vivas International Airport','Santo Domingo',49,898),
		('Munbil Airport','',8,418),
		('Louisa County Airport/Freeman Field','Louisa',39,738),
		('Coonamble Airport','',94,84),
		('Jutigalpa airport','Jutigalpa',97,608),
		('Oktyabrskiy Airport','Kzyl-Yar',89,585),
		('Middlemount Airport','',49,733),
		('Uljin Airport','Bongsan-ri, Uljin',87,843),
		('Sumbawanga Airport','Sumbawanga',90,99),
		('Manassas Regional Airport/Harry P. Davis Field','Manassas',27,580),
		('Candala Airport','Candala',74,337),
		('Falcon Field','Mesa',8,838),
		('Ust-Kuyga Airport','Ust-Kuyga',33,533),
		('Kumejima Airport','',84,386),
		('Patreksfjörður Airport','Patreksfjörður',8,776),
		('Petawawa Airport','Petawawa',90,255),
		('Koszalin Zegrze Pomorskie Air Base','Zegrze Pomorskie',34,805),
		('Keokuk Municipal Airport','Keokuk',77,49),
		('Ocean City Municipal Airport','Ocean City',24,589),
		('Munbil Airport','',25,993),
		('Miami Seaplane Base','Miami',8,235),
		('Agnew Airport','Agnew',38,100),
		('Daşoguz Airport','Daşoguz',20,800),
		('Araxos Airport','Patras',3,455),
		('Canobie Airport','Canobie',77,546),
		('Vodochody Airport','Vodochody',9,55),
		('Soroako Airport','Soroako-Celebes Island',80,555),
		('Yantai Laishan Airport','Yantai',73,739),
		('Sanderson Field','Shelton',73,806),
		('Compton Woodley Airport','Compton',52,26),
		('Sault Ste Marie Airport','Sault Ste Marie',16,497),
		('Henry E Rohlsen Airport','Christiansted',31,522),
		('Inta Airport','Inta',64,852),
		('Nullagine Airport','',47,683),
		('Napakiak Airport','Napakiak',75,761),
		('Sheppard Air Force Base-Wichita Falls Municipal Airport','Wichita Falls',81,905),
		('Nis Airport','Nis',85,82),
		('Central Jersey Regional Airport','Manville',45,949),
		('Salina Gunnison Airport','Salina',31,893),
		('Ihu Airport','Ihu',89,899),
		('Tela Airport','Tela',26,312),
		('Aguas Claras Airport','Ocaña',24,435),
		('Wunnumin Lake Airport','Wunnumin Lake',15,805),
		('La Guaira Airport','La Guaira',97,969),
		('General Ignacio P. Garcia International Airport','Hermosillo',70,1000),
		('Winnipeg / James Armstrong Richardson International Airport','Winnipeg',14,783),
		('Radom Airport','Radom',13,582),
		('Rurenabaque Airport','Rurenabaque',29,58),
		('Colonia Sarmiento Airport','Sarmiento',51,351),
		('Suffield Heliport','Suffield',93,510),
		('Cable Airport','Upland',95,468),
		('San Vito De Java Airport','Coto Brus',25,475),
		('Khmelnytskyi Airport','Khmelnytskyi',21,591),
		('Cartwright Airport','Cartwright',64,69),
		('Ailuk Airport','Ailuk Island',77,655),
		('Tchibanga Airport','Tchibanga',82,73),
		('Buffalo Spring','Samburu',14,794),
		('Bahía de los Ángeles Airport','Bahía de los Ángeles',9,633),
		('Hurghada International Airport','Hurghada',24,820),
		('Molde Airport','Årø',16,41),
		('Caen-Carpiquet Airport','Caen/Carpiquet',31,584),
		('Jinnah International Airport','Karachi',54,417),
		('Glasgow International Airport','Glasgow',27,719),
		('Hattiesburg Laurel Regional Airport','Hattiesburg/Laurel',70,721),
		('Senggeh Airport','Senggeh',21,387),
		('Montauban Airport','Montauban',86,628),
		('Prentice Airport','Prentice',65,96),
		('Garachiné Airport','Garachiné',36,858),
		('Arctic Village Airport','Arctic Village',48,445),
		('Ruston Regional Airport','Ruston',66,225),
		('Mayumba Airport','Mayumba',38,656),
		('Gostomel Airport','Kiev',90,796),
		('Rutland Plains Airport','',38,724),
		('Port Williams Seaplane Base','Port Williams',19,369),
		('Sfax Thyna International Airport','Sfax',19,687),
		('Yorke Island Airport','Yorke Island',12,542),
		('San Juan De Uraba Airport','San Juan De Uraba',28,976),
		('Grand Strand Airport','North Myrtle Beach',24,493),
		('Buckley Air Force Base','Aurora',25,519),
		('Luena Airport','Luena',4,544),
		('Cururupu Airport','Cururupu',30,537),
		('Bourges Airport','Bourges',60,829),
		('Sarajevo International Airport','Sarajevo',87,672),
		('Dutch Bay SPB','Kalpitiya Island',97,234),
		('Kampot Airport','Kampot',9,869),
		('Kursk East Airport','Kursk',69,223),
		('Lunyuk Airport','Lunyuk-Simbawa Island',67,195),
		('Phu Bai Airport','Hue',57,579),
		('Barrow Island Airport','',94,912),
		('Monroe Regional Airport','Monroe',14,993),
		('Eliye Springs Airport','Eliye Springs',86,886),
		('Dolpa Airport','Dolpa',61,404),
		('Tumling Tar Airport','Tumling Tar',5,854),
		('Shanshan Airport','Shanshan',48,38),
		('Paro Airport','Paro',66,539),
		('Long Seridan Airport','Long Seridan',100,418),
		('Lumbala Airport','Lumbala',46,829),
		('Wapenamanda Airport','',82,628),
		('Tri State Steuben County Airport','Angola',39,463),
		('Moyale Airport','Moyale (Lower)',72,952),
		('Quinhagak Airport','Quinhagak',25,10),
		('Lijiang Airport','Lijiang',34,279),
		('Punta Cana International Airport','Punta Cana',89,225),
		('Inca Manco Capac International Airport','Juliaca',92,922),
		('Rafsanjan Airport','',61,208),
		('Tirana International Airport Mother Teresa','Tirana',21,248),
		('Wiarton Airport','Wiarton',65,857),
		('Mittebah Airport','',15,25),
		('Tommy Kochon Airport','Colville Lake',68,504),
		('Toliara Airport','',55,438),
		('Pietermaritzburg Airport','Pietermaritzburg',94,829),
		('Algona Municipal Airport','Algona',8,102),
		('Ibadan Airport','Ibadan',41,631),
		('Bullfrog Basin Airport','Glen Canyon Natl Rec Area',96,306),
		('Yola Airport','Yola',51,729),
		('Bastia-Poretta Airport','Bastia/Poretta',56,458),
		('Griffiss International Airport','Rome',90,243),
		('Biarritz-Anglet-Bayonne Airport','Biarritz/Anglet/Bayonne',9,151),
		('Ratanakiri Airport','Ratanakiri',86,883),
		('Comandante Espora Airport','Bahia Blanca',49,320),
		('Hermiston Municipal Airport','Hermiston',62,841),
		('Dimbokro Airport','Dimbokro',34,396),
		('Artigas International Airport','Artigas',73,969),
		('Tavie Airport','Paama Island',50,182),
		('Mangole Airport, Falabisahaya','Mangole Island',79,373),
		('Aishalton Airport','Aishalton',47,430),
		('Vladivostok International Airport','Vladivostok',25,955),
		('Treasure Cay Airport','Treasure Cay',45,69),
		('Poum Airport','Poum',10,399),
		('Errol Airport','Errol',29,866),
		('Prominent Hill Airport','OZ Minerals Prominent Hill Mine',21,46),
		('Ovda International Airport','Eilat',39,269),
		('Illinois Valley Regional Airport-Walter A Duncan Field','Peru',68,301),
		('São Jorge Airport','Velas',13,691),
		('Manatee Airport','',72,1000),
		('Vivigani Airfield','Vivigani',46,308),
		('Lichinga Airport','Lichinga',63,920),
		('Söderhamn Airport','Söderhamn',24,135),
		('Panjgur Airport','Panjgur',41,465),
		('Alexander the Great International Airport','Kavala',99,141),
		('Puerto La Victoria Airport','Puerto La Victoria',95,308),
		('Tarfaya Airport','Tarfaya',72,584),
		('Kamaran Airport','Kamaran',5,435),
		('Whitecourt Airport','Whitecourt',8,246),
		('Buol Airport','Buol-Celebes Island',77,979),
		('Syktyvkar Airport','Syktyvkar',32,32),
		('RAF Wildenrath','British Armed Forces',97,213),
		('Rustaq Airport','Al Masna''ah',59,863),
		('Nice-Côte d''Azur Airport','Nice',14,777),
		('Yingkou Lanqi Airport','Yingkou',96,121),
		('Seinäjoki Airport','Seinäjoki / Ilmajoki',81,769),
		('Belaya Gora Airport','Belaya Gora',5,20),
		('Cooperstown-Westville Airport','Cooperstown',10,9),
		('Kratie Airport','Kratie',91,553),
		('Geraldton Greenstone Regional Airport','Geraldton',60,962),
		('Cessnock Airport','',40,384),
		('Dimapur Airport','Dimapur',79,641),
		('Borama Airport','Borama',80,141),
		('Diosdado Macapagal International Airport','Angeles/Mabalacat',47,445),
		('Reyes Airport','Reyes',66,938),
		('Watsonville Municipal Airport','Watsonville',85,306),
		('Sanderson Field','Shelton',25,734),
		('Buritirama Airport','Buritirama',29,303),
		('Dori Airport','Dori',91,812),
		('Denis Island Airport','Denis Island',8,65),
		('Knee Lake Airport','Knee Lake',48,434),
		('Sertanópolis Airport','Sertanópolis',96,246),
		('Hengchun Airport','Hengchung',74,956),
		('Al Massira Airport','Agadir',94,482),
		('Praia International Airport','Praia',25,80),
		('Lusk Municipal Airport','Lusk',66,763),
		('Priština International Airport','Prishtina',53,16),
		('Moranbah Airport','Moranbah',91,50),
		('Saúl Airport','Saúl',82,722),
		('Tengah Air Base','',49,304),
		('Barnstable Municipal Boardman Polando Field','Hyannis',18,474),
		('Lanseria Airport','Johannesburg',89,575),
		('Mandinga Airport','Condoto',96,519),
		('Westerland Sylt Airport','Westerland',63,300),
		('Tarakbits Airport','Tarakbits',40,521),
		('General Servando Canales International Airport','Matamoros',55,268),
		('Wotje Atoll Airport','Wotje Atoll',13,483),
		('Lindeman Island Airport','Lindeman Island',6,851),
		('Shimojishima Airport','Shimojishima',2,305),
		('Batuna Aerodrome','Batuna Mission Station',87,641),
		('Basanth Nagar Airport','Ramagundam',64,395),
		('Five Mile Airport','Five Mile',53,500),
		('Shire Inda Selassie Airport','Shire Indasilase',49,851),
		('Jerusalem Airport','Jerusalem',19,895),
		('Samangoky Airport','Tanandava',78,590),
		('Paris Issy-les-Moulineaux Heliport','Issy-les-Moulineaux',45,861),
		('Lake Rudolf Airport','Lake Rudolf',70,316),
		('Wiluna Airport','',15,337),
		('Sara Airport','Pentecost Island',6,658),
		('Sanandaj Airport','',63,98),
		('Tres De Mayo Airport','Puerto Asís',79,159),
		('Edwards Air Force Base','Edwards',20,617),
		('Itaqui Airport','Itaqui',25,141),
		('Coronel FAP Carlos Ciriani Santa Rosa International Airport','Tacna',74,7),
		('Ware Airport','Ware',60,431),
		('Greenvale Airport','',81,926),
		('Mélio Viana Airport','Três Corações',86,856),
		('Prince Rupert Airport','Prince Rupert',24,882),
		('Juan Santamaria International Airport','San Jose',24,899),
		('Batman Airport','Batman',15,611),
		('Ilam Airport','Ilam',60,987),
		('Lai Airport','Lai',73,255),
		('Propriano Airport','Propriano',17,935),
		('Xiangyang Liuji Airport','Xiangfan',74,641),
		('Tatakoto Airport','Tatakoto',34,358),
		('Mid-Carolina Regional Airport','Salisbury',20,824),
		('Inanwatan Airport','Inanwatan Airport-Papua Island',26,587),
		('Abemama Atoll Airport','Abemama Atoll',13,801),
		('Santana Ramos Airport','Santana Ramos',24,747),
		('Tabibuga Airport','Tabibuga',5,815),
		('Paris Beauvais Tillé Airport','Beauvais/Tillé',10,605),
		('Point Lay LRRS Airport','Point Lay',82,596),
		('Colmar-Houssen Airport','Colmar/Houssen',84,219),
		('Baita International Airport','Hohhot',75,651),
		('Big Bay Seaplane Base','Stuart Island',23,525),
		('Devi Ahilyabai Holkar Airport','Indore',15,135),
		('Boma Airport','Boma',29,438),
		('Tyler Pounds Regional Airport','Tyler',93,815),
		('Lecce Galatina Air Base','',88,193),
		('Nottingham Airport','Nottingham',8,231),
		('Yakataga Airport','Yakataga',98,839),
		('Erume Airport','Erume',37,245),
		('Rochester Airport','Rochester',84,416),
		('Valença Airport','Valença',91,390),
		('Warsaw Chopin Airport','Warsaw',13,769),
		('RAF Linton-On-Ouse','Linton-On-Ouse',39,996),
		('Proserpine Whitsunday Coast Airport','Proserpine',1,224),
		('Lonely Air Station','Lonely',70,797),
		('Lagoa Santa Airport','Lagoa Santa',52,449),
		('En Nahud Airport','En Nahud',4,167),
		('Richard Lloyd Jones Jr Airport','Tulsa',78,414),
		('Lorraine Airport','',72,285),
		('Andi Jemma Airport','Masamba-Celebes Island',18,378),
		('Arviat Airport','Arviat',66,807),
		('Corisco International Airport','Corisco Island',4,210),
		('Derby Field','Lovelock',1,484),
		('Bromont (Roland Desourdy) Airport','Bromont',69,986),
		('La Aurora Airport','Guatemala City',83,779),
		('David Constantijn Saudale Airport','Ba''a - Rote Island',91,492),
		('Tocumen International Airport','Tocumen',72,22),
		('Columbia Airport','Columbia',81,375),
		('Jacksonville Naval Air Station (Towers Field)','Jacksonville',72,828),
		('Sevilla Airport','Sevilla',82,433),
		('Manitouwadge Airport','Manitouwadge',17,835),
		('Skypark Airport','Bountiful',81,563),
		('Ngjiva Pereira Airport','Ngiva',35,794),
		('Chennai International Airport','Chennai',77,955),
		('Yuma MCAS/Yuma International Airport','Yuma',3,698),
		('Hinthada Airport','Hinthada',23,468),
		('Sasstown Airport','Sasstown',92,486),
		('Totegegie Airport','',93,442),
		('Nausori International Airport','Nausori',83,43),
		('Kryvyi Rih International Airport','Kryvyi Rih',4,970),
		('Cape Pole Seaplane Base','Cape Pole',95,555),
		('Savonlinna Airport','Savonlinna',73,406),
		('Ofu Village Airport','Ofu Village',77,306),
		('Boigu Airport','',96,916),
		('Peawanuck Airport','Peawanuck',50,38),
		('Valdosta Regional Airport','Valdosta',63,18),
		('Tilin Airport','Tilin',23,846),
		('Huallaga Airport','Bellavista',52,300),
		('Magaruque Airport','Magaruque Island',38,345),
		('Bogashevo Airport','Tomsk',45,866),
		('Tehuacan Airport','',85,405),
		('Rewa Airport, Chorhata, REWA','Rewa',17,114),
		('Capital International Airport','',32,196),
		('Jamestown Regional Airport','Jamestown',10,706),
		('Tullahoma Regional Arpt/Wm Northern Field','Tullahoma',79,246),
		('Riverton Regional Airport','Riverton',74,986),
		('Linfen Qiaoli Airport','Linfen',98,945),
		('Kamphaeng Saen Airport','Nakhon Pathom',68,486),
		('Eastern WV Regional Airport/Shepherd Field','Martinsburg',36,695),
		('Faleolo International Airport','Apia',28,665),
		('Namibe Airport','Namibe',56,857),
		('Lhok Sukon Airport','Lhok Sukon-Sumatra Island',86,209),
		('Maribor Airport','',55,510),
		('Dikson Airport','Dikson',38,734),
		('Bade Airport','Bade',91,820),
		('Sofia Airport','Sofia',36,447),
		('Bristol Airport','Bristol',24,242),
		('Alta Airport','Alta',32,966),
		('Iqaluit Airport','Iqaluit',8,803),
		('Yamagata Airport','Yamagata',6,539),
		('Ástor Piazzola International Airport','Mar del Plata',28,905),
		('Clovis Municipal Airport','Clovis',89,860),
		('Yam Island Airport','Yam Island',5,405),
		('Ilam Airport','Ilam',80,545),
		('Platinum Airport','Platinum',92,729),
		('Bromont (Roland Desourdy) Airport','Bromont',27,441),
		('Manokotak Airport','Manokotak',55,328),
		('Spring Point Airport','Spring Point',33,373),
		('Leeward Point Field','Guantanamo Bay Naval Station',55,399),
		('Lindeman Island Airport','Lindeman Island',74,534),
		('Havre St Pierre Airport','Havre St-Pierre',88,352),
		('Jaipur International Airport','Jaipur',12,437),
		('Mt. Fuji Shizuoka Airport','Makinohara / Shimada',85,162),
		('Bowman Field','Louisville',11,408),
		('El Maiten Airport','El Maiten',76,135),
		('Roscommon County - Blodgett Memorial Airport','Houghton Lake',48,317),
		('Mount Gunson Airport','Mount Gunson',78,75),
		('Boralday Airport','Aima Ata',77,82),
		('Aberdeen Dyce Airport','Aberdeen',80,187),
		('Chañaral Airport','Chañaral',55,611),
		('Palmerston North Airport','',81,706),
		('Bulimba Airport','',56,247),
		('Faya Largeau Airport','',82,903),
		('Casa De Campo International Airport','La Romana',56,990),
		('Maranggo Airport','Waha-Tomea Island',98,652),
		('Pulau Pangkor Airport','Pangkor Island',21,343),
		('King Khaled International Airport','Riyadh',81,662),
		('Pickle Lake Airport','Pickle Lake',59,117),
		('Gassim Airport','',100,565),
		('Malta International Airport','Valletta',76,324),
		('Futaleufú Airport','Futaleufu',51,485),
		('Hami Airport','Hami',52,523),
		('Dalby Airport','',46,942),
		('Dease Lake Airport','Dease Lake',55,187),
		('Saïss Airport','Fes',64,367),
		('Mandalgobi Airport','Mandalgobi',34,782),
		('Corryong Airport','',25,669),
		('Congonhas Airport','São Paulo',22,21),
		('Whatì Airport','Whatì',8,675),
		('Simara Airport','Simara',9,581),
		('Gettysburg Regional Airport','Gettysburg',18,876),
		('Juscelino Kubitscheck Airport','Teófilo Otoni',13,739),
		('Kefallinia Airport','Kefallinia Island',7,661),
		('Taylor Airport','Taylor',88,802),
		('Singapore Changi Airport','Singapore',38,305),
		('Salem Airport','Salem',84,869),
		('Tepoe Airstrip','Kasikasima',45,886),
		('Medfra Airport','Medfra',59,510),
		('Calabozo Airport','Guarico',99,997),
		('Atikokan Municipal Airport','Atikokan',78,888),
		('Wiluna Airport','',72,992),
		('Bezmer Air Base','Yambol',16,98),
		('Luiza Airport','Luiza',53,333),
		('Marlboro County Jetport H.E. Avent Field','Bennettsville',85,360),
		('John A. Osborne Airport','Gerald''s Park',76,1),
		('Camp Page Airport (A-306)','Chun Chon City',88,220),
		('Khabarovsk-Novy Airport','Khabarovsk',98,200),
		('Maria Reiche Neuman Airport','Nazca',33,537),
		('Monastir Habib Bourguiba International Airport','Monastir',64,336),
		('Macaé Airport','Macaé',54,195),
		('Fagali''i Airport','Apia',68,902),
		('Cheboksary Airport','Cheboksary',28,899),
		('Cassilândia Airport','Cassilândia',39,775),
		('Nhon Co Airfield','Quang Duc',36,326),
		('Tambillos Airport','Coquimbo',22,930),
		('Minami Torishima Airport','',74,769),
		('Singita Safari Lodge Airport','Singita Safari Lodge',29,2),
		('Hukuntsi Airport','Hukuntsi',61,523),
		('Nadi International Airport','Nadi',11,496),
		('La Güera Airport','La Güera',3,719),
		('Harry Stern Airport','Wahpeton',23,213),
		('Ames Municipal Airport','Ames',32,574),
		('Tureia Airport','',11,330),
		('Redenção Airport','Redenção',48,853),
		('Nain Airport','Nain',100,320),
		('Nuremberg Airport','Nuremberg',30,318),
		('Kalumburu Airport','',9,232),
		('Ponta do Ouro Airport','Ponta do Ouro',90,446),
		('St George Municipal Airport','St George',91,327),
		('Ossima Airport','Ossima',4,457),
		('Volta Redonda Airport','Volta Redonda',46,927),
		('Tambolaka Airport','Waikabubak-Sumba Island',70,250),
		('Dornoch Airfield','Dornoch',3,274),
		('Punta Colorada Airport','La Ribera',72,447),
		('Lille-Lesquin Airport','Lille/Lesquin',16,341),
		('Split Airport', 'Split', 25, 874);
		
